import {createContext} from "react";

export const MovieContext = createContext();

export const data = [
  {
    mal_id: 1,
    title: "When Marnie Was There",
    synopsis:
      "The film follows Anna Sasaki living with her relatives in the seaside town. Anna comes across a nearby abandoned mansion, where she meets Marnie, a mysterious girl who asks her to promise to keep their secrets from everyone. As the summer progresses, Anna spends more time with Marnie, and eventually Anna learns the truth about her family and foster care.",
    director: "Hiromasa Yonebayashi",
    airing_start: "2014",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img1.jpg?alt=media&token=26c754ed-98b3-4407-a06e-d49c7174eb05",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 2,
    title: "The Tale of the Princess Kaguya",
    synopsis:
      "A bamboo cutter named Sanuki no Miyatsuko discovers a miniature girl inside a glowing bamboo shoot. Believing her to be a divine presence, he and his wife decide to raise her as their own, calling her 'Princess'.",
    director: "Isao Takahata",
    airing_start: "2013",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img2.jpg?alt=media&token=bdfd4693-93ea-4ede-90ca-fc0c0e1633a3",
    alt: "poster",
    score: 8.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 3,
    title: "The Wind Rises",
    synopsis:
      "A lifelong love of flight inspires Japanese aviation engineer Jiro Horikoshi, whose storied career includes the creation of the A-6M World War II fighter plane.",
    director: "Hayao Miyazaki",
    airing_start: "2013",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img3.jpg?alt=media&token=131e06c8-a0ee-4564-ad21-856f27b0e994",
    alt: "poster",
    score: 7.8,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 4,
    title: "From Up on Poppy Hill",
    synopsis:
      " The story is set in 1963 in Yokohama. Kokuriko Manor sits on a hill overlooking the harbour. A 16 year-old girl, Umi, lives in that house. Every morning she raises a signal flag facing the sea. The flag means “I pray for safe voyages”. A 17 year-old boy, Shun, always sees this flag from the sea as he rides a tugboat to school. Gradually the pair are drawn to each other but they are faced with a sudden trial. Even so, they keep going without running from facing the hardships of reality.",
    director: "Gorō Miyazaki",
    airing_start: "2011",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img4.jpg?alt=media&token=47e4090f-7005-47e7-a79d-52600739c4a7",
    alt: "poster",
    score: 8.2,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 5,
    title: "Arrietty",
    synopsis:
      "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity as they make their own home from items 'borrowed' from the house's human inhabitants. However, life changes for the Clocks when a human boy discovers Arrietty.",
    director: "Hiromasa Yonebayashi",
    airing_start: "2010",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img5.png?alt=media&token=96eeb661-c9ae-4579-aabd-2c2b8cfd286e",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 6,
    title: "Ponyo",
    synopsis:
      "The son of a sailor, 5-year old Sosuke lives a quiet life on an oceanside cliff with his mother Lisa. One fateful day, he finds a beautiful goldfish trapped in a bottle on the beach and upon rescuing her, names her Ponyo. But she is no ordinary goldfish. The daughter of a masterful wizard and a sea goddess, Ponyo uses her father's magic to transform herself into a young girl and quickly falls in love with Sosuke, but the use of such powerful sorcery causes a dangerous imbalance in the world. As the moon steadily draws nearer to the earth and Ponyo's father sends the ocean's mighty waves to find his daughter, the two children embark on an adventure of a lifetime to save the world and fulfill Ponyo's dreams of becoming human.",
    director: "Hayao Miyazaki",
    airing_start: "2008",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img6.jpg?alt=media&token=5c14e3b3-99ea-4e18-9f57-442d5e35b049",
    alt: "poster",
    score: 9.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 7,
    title: "Tales from Earthsea",
    synopsis:
      "Something bizarre has come over the land. The kingdom is deteriorating. People are beginning to act strange... What's even more strange is that people are beginning to see dragons, which shouldn't enter the world of humans. Due to all these bizarre events, Ged, a wandering wizard, is investigating the cause. During his journey, he meets Prince Arren, a young distraught teenage boy. While Arren may look like a shy young teen, he has a severe dark side, which grants him strength, hatred, ruthlessness and has no mercy, especially when it comes to protecting Teru. For the witch Kumo this is a perfect opportunity. She can use the boy's 'fears' against the very one who would help him, Ged.",
    director: "Gorō Miyazaki",
    airing_start: "2006",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img7.jpg?alt=media&token=8d89896b-e0b1-4fe0-943a-353522479019",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 8,
    title: "Howl's Moving Castle",
    synopsis:
      "When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking home.",
    director: "Hayao Miyazaki",
    airing_start: "2004",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img8.jpg?alt=media&token=a949db38-5204-43e1-afec-f8550568ba90",
    alt: "poster",
    score: 7,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 9,
    title: "The Cat Returns",
    synopsis:
      "Haru, a schoolgirl bored by her ordinary routine, saves the life of an unusual cat and suddenly her world is transformed beyond anything she ever imagined. The Cat King rewards her good deed with a flurry of presents, including a very shocking proposal of marriage to his son! Haru embarks on an unexpected journey to the Kingdom of Cats where her eyes are opened to a whole other world.",
    director: "Hiroyuki Morita",
    airing_start: "2002",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img9.jpg?alt=media&token=d24c8129-c2e3-4a01-9041-cef0391fbe26",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 10,
    title: "Spirited Away",
    synopsis:
      " Spirited Away is an Oscar winning Japanese animated film about a ten year old girl who wanders away from her parents along a path that leads to a world ruled by strange and unusual monster-like animals. Her parents have been changed into pigs along with others inside a bathhouse full of these creatures. Will she ever see the world how it once was?",
    director: "Hayao Miyazaki",
    airing_start: "2001",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img10.jpg?alt=media&token=a781eda7-35b1-4ac4-b534-755897adf1ad",
    alt: "poster",
    score: 9,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 11,
    title: "My Neighbors the Yamadas",
    synopsis:
      "The Yamadas are a typical middle class Japanese family in urban Tokyo and this film shows us a variety of episodes of their lives. With tales that range from the humourous to the heartbreaking, we see this family cope with life's little conflicts, problems and joys in their own way.",
    director: "Isao Takahata",
    airing_start: "1999",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img11.jpg?alt=media&token=4f4c9cad-a06b-4ad9-9522-8a4cee05603e",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 12,
    title: "Princess Mononoke",
    synopsis:
      "Ashitaka, a prince of the disappearing Ainu tribe, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
    director: "Hayao Miyazaki",
    airing_start: "1997",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img12.jpg?alt=media&token=332dfe68-241d-4272-b419-056e508c75f5",
    alt: "poster",
    score: 8.2,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 13,
    title: "Whisper of the Heart",
    synopsis:
      "Shizuku lives a simple life, dominated by her love for stories and writing. One day she notices that all the library books she has have been previously checked out by the same person: 'Seiji Amasawa'. Curious as to who he is, Shizuku meets a boy her age whom she finds infuriating, but discovers to her shock that he is her 'Prince of Books'. As she grows closer to him, she realises that he merely read all those books to bring himself closer to her. The boy Seiji aspires to be a violin maker in Italy, and it is his dreams that make Shizuku realise that she has no clear path for her life. Knowing that her strength lies in writing, she tests her talents by writing a story about Baron, a cat statuette belonging to Seiji's grandfather.",
    director: "Yoshifumi Kondō",
    airing_start: "1995",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img13.png?alt=media&token=44544a18-a3f1-40b3-adf5-bc4ab3d70c07",
    alt: "poster",
    score: 8.86,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 14,
    title: "Pom Poko",
    synopsis:
      "As the human city development encroaches on the raccoon population's forest and meadow habitat, the raccoons find themselves faced with the very real possibility of extinction. In response, the raccoons engage in a desperate struggle to stop the construction and preserve their home.",
    director: "Isao Takahata",
    airing_start: "1994",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img14.jpg?alt=media&token=a891716f-761a-4f45-8e5e-8e2351dc2cc6",
    alt: "poster",
    score: 7.52,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 15,
    title: "Porco Rosso",
    synopsis:
      "Porco Rosso, known in Japan as Crimson Pig (Kurenai no Buta) is the sixth animated film by Hayao Miyazaki and released in 1992. You're introduced to an Italian World War I fighter ace, now living as a freelance bounty hunter chasing 'air pirates' in the Adriatic Sea. He has been given a curse that changed his head to that of a pig. Once called Marco Pagot, he is now known to the world as 'Porco Rosso', Italian for 'Red Pig.'",
    director: "Hayao Miyazaki",
    airing_start: "1992",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img15.jpg?alt=media&token=aed4d187-2198-428c-bbdc-788941fd3d8a",
    alt: "poster",
    score: 7.72,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 16,
    title: "Only Yesterday",
    synopsis:
      " It’s 1982, and Taeko is 27 years old, unmarried, and has lived her whole life in Tokyo. She decides to visit her family in the countryside, and as the train travels through the night, memories flood back of her younger years: the first immature stirrings of romance, the onset of puberty, and the frustrations of math and boys. At the station she is met by young farmer Toshio, and the encounters with him begin to reconnect her to forgotten longings. In lyrical switches between the present and the past, Taeko contemplates the arc of her life, and wonders if she has been true to the dreams of her childhood self.",
    director: "Isao Takahata",
    airing_start: "1991",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img16.jpg?alt=media&token=fcdd00d1-d06b-4ee4-8658-cb698c669465",
    alt: "poster",
    score: 7.82,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 17,
    title: "Kiki's Delivery Service",
    synopsis:
      "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
    director: "Hayao Miyazaki",
    airing_start: "1989",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img17.jpg?alt=media&token=4266f7b4-a7f5-49ec-ac96-7b950bbe8c7e",
    alt: "poster",
    score: 8,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 18,
    title: "My Neighbor Totoro",
    synopsis:
      "Two sisters move to the country with their father in order to be closer to their hospitalized mother, and discover the surrounding trees are inhabited by Totoros, magical spirits of the forest. When the youngest runs away from home, the older sister seeks help from the spirits to find her.",
    director: "Hayao Miyazaki",
    airing_start: "1988",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img18.jpg?alt=media&token=cb26a4cc-88ca-43fc-b2e5-fbdde9deaf20",
    alt: "poster",
    score: 7.1,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 19,
    title: "Grave of the Fireflies",
    synopsis:
      " In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.",
    director: " Isao Takahata",
    airing_start: "1988",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img19.jpg?alt=media&token=db56ae36-783e-40a9-a1bf-ce94cf6a9b63",
    alt: "poster",
    score: 6.2,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 20,
    title: "Castle in the Sky",
    synopsis:
      "The orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world.",
    director: "Hayao Miyazaki",
    airing_start: "1986",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img20.jpg?alt=media&token=792bc333-912b-4c9b-bdc6-b06a591f368c",
    alt: "poster",
    score: 8.9,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 21,
    title: "Your Name",
    synopsis:
      "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another. Kimi no Na wa. revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance.",
    director: "Makoto Shinkai",
    airing_start: "2016",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img21.jpg?alt=media&token=9664cc01-218f-4232-ac00-41d96f04df9f",
    alt: "poster",
    score: 9.0,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 22,
    title: "A Silent Voice",
    synopsis:
      "As a wild youth, elementary school student Shouya Ishida sought to beat boredom in the cruelest ways. When the deaf Shouko Nishimiya transfers into his class, Shouya and the rest of his class thoughtlessly bully her for fun. However, when her mother notifies the school, he is singled out and blamed for everything done to her. With Shouko transferring out of the school, Shouya is left at the mercy of his classmates. He is heartlessly ostracized all throughout elementary and middle school, while teachers turn a blind eye. Now in his third year of high school, Shouya is still plagued by his wrongdoings as a young boy. Sincerely regretting his past actions, he sets out on a journey of redemption: to meet Shouko once more and make amends. Koe no Katachi tells the heartwarming tale of Shouya's reunion with Shouko and his honest attempts to redeem himself, all while being continually haunted by the shadows of his past.",
    director: "Naoko Yamada",
    airing_start: "2016",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img22.jpg?alt=media&token=f4a8276b-8e52-4f9e-86bb-126299723fa4",
    alt: "poster",
    score: 9.01,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 23,
    title: "Doukyuusei",
    synopsis:
      "Hikaru Kusakabe is a normal, carefree boy in a rock band who is always focused on the present. During the summer, his entire class is forced to participate in an upcoming chorus festival. By coincidence, he discovers his classmate Rihito Sajou—known for being an honor student with excellent grades—practicing his singing alone. Sajou just cannot seem to get their class' song right, and Kusakabe, delighted at seeing a new side of his straight-laced classmate, offers to help him prepare for the event. Although their lives and personalities are total opposites, they begin to grow closer as time progresses. But with the pressure of an unknown future, what will become of them and their growing relationship?",
    director: "Shouko Nakamura",
    airing_start: "2016",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img23.jpg?alt=media&token=84f22ec3-6288-4869-bfb4-f1554219269f",
    alt: "poster",
    score: 8.3,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 24,
    title: "Wolf Children",
    synopsis:
      "Hana, a hard-working college student, falls in love with a mysterious man who attends one of her classes though he is not an actual student. As it turns out, he is not truly human either. On a full moon night, he transforms, revealing that he is the last werewolf alive. Despite this, Hana's love remains strong, and the two ultimately decide to start a family. Hana gives birth to two healthy children—Ame, born during rainfall, and Yuki, born during snowfall—both possessing the ability to turn into wolves, a trait inherited from their father. All too soon, however, the sudden death of her lover devastates Hana's life, leaving her to raise a peculiar family completely on her own. The stress of raising her wild-natured children in a densely populated city, all while keeping their identity a secret, culminates in a decision to move to the countryside, where she hopes Ame and Yuki can live a life free from the judgments of society. Wolf Children is the heartwarming story about the challenges of being a single mother in an unforgiving modern world.",
    director: "Mamoru Hosoda",
    airing_start: "2012",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img24.jpg?alt=media&token=35199384-6130-4ace-9a4f-a911e1122da4",
    alt: "poster",
    score: 8.66,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 25,
    title: "Saezuru Tori wa Habatakanai: The Clouds Gather",
    synopsis:
      "Yashiro is the young leader of Shinseikai and the president of the Shinseikai Enterprise, but like so many powerful men, he leads a double life as a deviant and a masochist. Doumeki Chikara comes to work as a bodyguard for him and, although Yashiro had decided that he would never lay a hand on his own men, he finds there's something about Doumeki that he can't resist. Yashiro makes advances toward Doumeki, but Doumeki has mysterious reasons for denying. Yashiro, who abuses his power just to abuse himself, and Doumeki, who faithfully obeys his every command, begin the tumultuous affair of two men with songs in their hearts and no wings to fly.",
    director: "Kaori Makita",
    airing_start: "2020",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img25.jpg?alt=media&token=7a557736-062c-4519-8f73-c36ef12a7f05",
    alt: "poster",
    score: 7.61,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 26,
    title: "Colorful",
    synopsis:
      "Upon arriving at the train station of death, an impure soul is granted a second chance at life against his will. Reincarnating into the body of Makoto Kobayashi, a 14-year-old boy who recently committed suicide, the soul is tasked to identify the boy's greatest sin in life within a time limit of six months. Although it remains reluctant toward continuing life as Makoto, the soul soon begins to notice the complexities of people's emotions and actions. Deconstructing the ideas of fractured families and suicide, Colorful explores the intricacies of the daily struggles humans face but are too abashed to confront.",
    director: "Keiichi Hara",
    airing_start: "2010",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img26.jpg?alt=media&token=74ccea27-94a2-4ab5-9680-25ad98a179b6",
    alt: "poster",
    score: 7.85,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 27,
    title: "The Garden of Words",
    synopsis:
      "On a rainy morning in Tokyo, Takao Akizuki, an aspiring shoemaker, decides to skip class to sketch designs in a beautiful garden. This is where he meets Yukari Yukino, a beautiful yet mysterious woman, for the very first time. Offering to make her new shoes, Takao continues to meet with Yukari throughout the rainy season, and without even realizing it, the two are able to alleviate the worries hidden in their hearts just by being with each other. However, their personal struggles have not disappeared completely, and as the end of the rainy season approaches, their relationship will be put to the test.",
    director: "Makoto Shinkai",
    airing_start: "2013",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img27.jpg?alt=media&token=98b2a425-c87a-4393-9ea9-95f080f38bee",
    alt: "poster",
    score: 8.09,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 28,
    title: "Kimi no Suizou wo Tabetai",
    synopsis:
      "The aloof protagonist: a bookworm who is deeply detached from the world he resides in. He has no interest in others and is firmly convinced that nobody has any interest in him either. His story begins when he stumbles across a handwritten book, titled \"Living with Dying.\" He soon identifies it as a secret diary belonging to his popular, bubbly classmate Sakura Yamauchi. She then confides in him about the pancreatic disease she is suffering from and that her time left is finite. Only her family knows about her terminal illness; not even her best friends are aware. Despite this revelation, he shows zero sympathy for her plight, but caught in the waves of Sakura's persistent buoyancy, he eventually concedes to accompanying her for her remaining days. As the pair of polar opposites interact, their connection strengthens, interweaving through their choices made with each passing day. Her apparent nonchalance and unpredictability disrupts the protagonist's impassive flow of life, gradually opening his heart as he discovers and embraces the true meaning of living.",
    director: "Shin'ichirō Ushijima",
    airing_start: "2018",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img28.jpg?alt=media&token=ca97d0c5-f101-440a-bb8f-2e0e7ab97aba",
    alt: "poster",
    score: 8.6,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 29,
    title: "The Girl Who Leapt Through Time",
    synopsis:
      "Makoto Konno is in her last year of high school, but is having a hard time deciding what to do with her future. In between enduring the pressure of her teachers and killing time with her best friends, Makoto's life suddenly changes when she accidentally discovers that she is capable of literally leaping through time. Toki wo Kakeru Shoujo follows Makoto as she plays around with her newfound power. However, she soon learns the hard way that every choice has a consequence, and time is a lot more complicated than it may seem.",
    director: "Mamoru Hosoda",
    airing_start: "2006",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img29.jpg?alt=media&token=4375c3b4-a59e-45e4-a131-e19d616092bc",
    alt: "poster",
    score: 8.22,
    episodes: 1,
    type: "Movie",
  },
  {
    mal_id: 30,
    title: "Shikioriori",
    synopsis:
      "The rigorous city life of China, while bustling and unforgiving, contains the everlasting memories of days past. Three stories told in three different cities, Shikioriori follows the loss of youth and the daunting realization of adulthood. Though reality may seem ever changing, unchangeable are the short-lived moments of one's childhood days. A plentiful bowl of noodles, the beauty of family and the trials of first love endure the inevitable flow of time, as three different characters explore the strength of bonds and the warmth of cherished memories. Within the disorder of the present world, witness these quaint stories recognize the comfort of the past, and attempt to revive the neglected flavors of youth.",
    director: "Li Haoling, Jiaoshou Yi Xiaoxing, Yoshitaka Takeuchi",
    airing_start: "2018",
    image_url: "https://firebasestorage.googleapis.com/v0/b/photo-storage-9945c.appspot.com/o/img30.jpg?alt=media&token=8d067622-a91c-41a7-873f-1ad22973f21f",
    alt: "poster",
    score: 7.19,
    episodes: 1,
    type: "Movie",
  },
];
